### ISSUE TITLE
🐛 bug: `Copy Room Link` not working

### ISSUE THREAD

**Issue by tusharnankani** [prince776/discode#2]
The `Copy Room Link` is not working. When clicked, it copies this `//room/1`

![image](https://user-images.githubusercontent.com/61280281/119174330-14a9fa00-ba86-11eb-9d52-8d11e30bfcff.png)

https://github.com/prince776/discode/blob/c9e6bf941f8892e6e0ede3199e34c61cf5f258bd/frontend/src/config/config.ts#L1-L3

Maybe because this is the baseURL and not the one that is hosted currently.

https://github.com/prince776/discode/blob/c9e6bf941f8892e6e0ede3199e34c61cf5f258bd/frontend/src/pages/room.tsx#L383

**Comment by prince776** [comment]
Yes, that's exactly the reason why it doesn't work. Now I'm thinking I can add another env variable for `DNS_NAME` or something better which be used during deployment. If you have a better solution do suggest.

P.S: Deploying it might take some time since CI is not setup and I'll have to manually deploy

**Comment by HarshKapadia2** [comment]
Hey @prince776, I think you can use the [URL interface](https://developer.mozilla.org/en-US/docs/Web/API/URL) to extract the base URL.

Example:
![image](https://user-images.githubusercontent.com/50140864/119220763-b9b9e680-bb09-11eb-8de3-c80b928e9cff.png)

A good reference video: [HTML5 URL and SearchParams Objects](https://www.youtube.com/watch?v=b867xRQkjVA&list=PLyuRouwmQCjmQTKvgqIgah03HF1wrYkA9&index=166)

**Comment by HarshKapadia2** [comment]
Instead of this, just using the `window.location` object will work as well.
Credits: @KartikSoneji

**Comment by prince776** [comment]
Will add `window.location.href` to production code for now. Will fix it soon, once I'm free.

Thanks for the suggestions and making my life easy. Feel free to open a PR if you desire.

**Comment by tusharnankani** [comment]
@HarshKapadia2 Go ahead 👍🏻
