### ISSUE TITLE
[enhancement] change URL implementation

### ISSUE THREAD

**Issue by tusharnankani** [prince776/discode#3]
It allows us to create multiple rooms with the same room name. Is this supposed to behave this way with duplicate entries? 

Though, I would understand since your URL is based on a number that keeps incrementing, and not based on the room name. 

![image](https://user-images.githubusercontent.com/61280281/119175606-a6663700-ba87-11eb-8012-e2fb970e9932.png)

However, I feel a system with random *alpha-numeric* addition (slug) to the URL, like Google Meet or any URL shortener, (instead of the incrementing number approach, because right now, I could simply put any number below the current room number, and we can get access to the code and voice conversations), will help maintain **privacy** and *no disruption or deletion of code*. 

Simply because the generated URL will be difficult to guess. And this way you *might* not need a way to authenticate a user, since the link will be only shared with the **trusted users**.

**Comment by prince776** [comment]
Yes, great suggestion about alpha-numeric code, will be implementing it, it'll require a little bit of refactoring as well.
Also about titles, I believe many people would want to use the same room name so having them be duplicate is intended

**Comment by prince776** [comment]
Implemented in c4b2882915c472f1dcd4fbc6d859fdbaba965cd5.
Closing.
